schema_version: 1

context:
  version: "2.10.2"

package:
  name: e3sm-quickview
  version: ${{ version }}

source:
  url: https://files.pythonhosted.org/packages/7f/09/910f9467fd5f3496009af11dabc6f3070bc0d0b7809aa59112c26b97de73/e3sm_quickview-${{ version }}.tar.gz
  sha256: 47439329ccb5628e07d4ec12ed62cb73fd9a2b61138d8194d8980fc80199f46e

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - quickview = e3sm_quickview.app:main

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - pip
  run:
    - python >=${{ python_min }}
    - paraview >=6
    - hdf5 <2
    - wslink >=2.5.7
    - trame >=3.13.2
    - trame-rca >=2.6
    - trame-vuetify >=3.1
    - pyproj >=3.6.1
    - netcdf4 >=1.6.5
    - trame-dataclass >=2.0.2
    - trame-components
    - trame-tauri >=0.6.2
    - trame-colormaps >=1.7.2
    - pillow

tests:
  - python:
      python_version:
        - ${{ python_min }}.*
        - "*"
      imports:
        - e3sm_quickview
      pip_check: true
  - requirements:
      run:
        - pip
    script:
      - quickview --help

about:
  summary: An application to explore/analyze data for atmosphere component for E3SM
  license: Apache-2.0
  license_file: LICENSE
  homepage: https://pypi.org/project/e3sm-quickview/

extra:
  recipe-maintainers:
    - huiwanpnnl
    - jourdain
    - psavery
    - alesgenova
